Description: Set up CloudFront Distribution and Route53 DNS for the static site

Resources:
  MyCloudFrontOAI:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "OAI for S3 bucket access"

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - Id: S3Origin
            DomainName: static-site.jiwanheo.xyz
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${MyCloudFrontOAI}"
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https # Ensure HTTPS is enforced
          AllowedMethods:
            - GET
            - HEAD
          CachedMethods:
            - GET
            - HEAD
          ForwardedValues:
            QueryString: false # Do not forward query strings to S3
            Cookies:
              Forward: none # Do not forward cookies
        ViewerCertificate:
          AcmCertificateArn: !ImportValue MySSLCertificateStack-CertificateArn
          SslSupportMethod: sni-only
        Enabled: true
        DefaultRootObject: index.html
        HttpVersion: http2
        PriceClass: PriceClass_100 # Use the cheapest price class (optional)

  # S3 Bucket Policy to allow CloudFront access
  CloudFrontAccessS3Policy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: static-site.jiwanheo.xyz
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowCloudFrontAccess"
            Effect: "Allow"
            Principal:
              AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${MyCloudFrontOAI}
            Action: "s3:GetObject"
            Resource: arn:aws:s3:::static-site.jiwanheo.xyz/*

  Route53DNSRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneId: Z066358329E65RHIEOJXQ # Replace with your actual hosted zone ID
      Name: static-site.jiwanheo.xyz
      Type: A
      AliasTarget:
        DNSName: !GetAtt CloudFrontDistribution.DomainName # CloudFront distribution domain name
        HostedZoneId: Z2FDTNDATAQYW2
# Outputs:
#   CloudFrontDomainName:
#     Description: CloudFront Distribution Domain Name
#     Value: !GetAtt CloudFrontDistribution.DomainName
