Resources:
  S3ForStaticSite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: static-site.jiwanheo.xyz
      VersioningConfiguration:
        Status: Enabled # Enable versioning if needed
      WebsiteConfiguration:
        IndexDocument: index.html

  S3ForLambda:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lambda-for-static-site.jiwanheo.xyz
      VersioningConfiguration:
        Status: Enabled # Enable versioning if needed

  S3ForCloudFrontLogs:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: cloudfront-logs.jiwanheo.xyz
      VersioningConfiguration:
        Status: Enabled # Enable versioning if needed

  CloudFrontLogBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3ForCloudFrontLogs
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: "AllowCloudWatchLogs"
            Effect: "Allow"
            Principal:
              Service: "logs.amazonaws.com"
            Action: "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::${S3ForCloudFrontLogs}/*"
            Condition:
              StringEquals:
                aws:SourceAccount: !Sub "${AWS::AccountId}"

Outputs:
  S3BucketName:
    Value: !Ref S3ForStaticSite
    Description: "The name of the S3 bucket"
    Export:
      Name: StaticSiteS3BucketName

  S3DomainName:
    Value: !GetAtt S3ForStaticSite.DomainName
    Export:
      Name: S3BucketDomainName # This name will be referenced by other stacks

  CloudFrontLogBucketDomainName:
    Value: !GetAtt S3ForCloudFrontLogs.DomainName
    Description: "The name of the S3 bucket"
    Export:
      Name: CloudFrontLogS3BucketNameDomainName
