Resources:
  S3ForStaticSite:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: static-site.jiwanheo.xyz
      VersioningConfiguration:
        Status: Enabled # Enable versioning if needed

  S3ForLambda:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: lambda-for-static-site.jiwanheo.xyz
      VersioningConfiguration:
        Status: Enabled # Enable versioning if needed

Outputs:
  S3DomainName:
    Value: !GetAtt S3ForStaticSite.DomainName
    Export:
      Name: S3BucketDomainName # This name will be referenced by other stacks
