Resources:
  MySSLCertificate:
    Type: AWS::ACM::Certificate
    Properties:
      DomainName: static-site.jiwanheo.xyz
      ValidationMethod: DNS # Use DNS validation

  # MyDNSValidationRecord:
  #   Type: AWS::Route53::RecordSet
  #   Properties:
  #     HostedZoneId: "Z2P70J7EXAMPLE"  # Replace with your actual Hosted Zone ID
  #     Name: !GetAtt MySSLCertificate.DomainValidationOptions.0.ResourceRecord.Name
  #     Type: CNAME
  #     TTL: '60'
  #     ResourceRecords:
  #       - !GetAtt MySSLCertificate.DomainValidationOptions.0.ResourceRecord.Value

Outputs:
  CertificateArn:
    Description: "ARN of the SSL certificate"
    Value: !Ref MySSLCertificate
