Description: Set up usage notification and action

Resources:
  MySnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: static-site-high-requests
      Subscription:
        - Protocol: email
          Endpoint: jiwanheo123@gmail.com
