name: Deploy Next.js to S3

on:
  push:
    branches:
      - phase4 # Trigger on push to main branch
  pull_request:
    branches:
      - main # Trigger on PRs targeting the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # This specifies the environment the job will run in

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the code from your repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "v21.7.1" # Specify the Node.js version you want to use

      - name: Install dependencies
        run: |
          cd site  # Navigate to the 'site' directory
          npm install  # Now 'npm install' will work in the correct directory

      - name: Build the app
        run: |
          cd site  # Make sure we are in the 'site' directory
          npm run build  # Run the build process

      - name: Deploy to S3
        run: |
          cd site  # Ensure we are in the 'site' directory
          aws s3 sync out/ s3://static-site.jiwanheo.xyz --exact-timestamps --delete  # Deploy the 'out' folder to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-east-2"
