name: Deploy Next.js to S3

on:
  push:
    branches:
      - phase2 # This will trigger the workflow when you push to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # This specifies the environment the job will run in

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # Checkout the code from your repository

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "v21.7.1" # Specify the Node.js version you want to use

      - name: Install dependencies
        run: |
          cd site  # Navigate to the 'site' directory
          npm install  # Now 'npm install' will work in the correct directory

      - name: Build the app
        run: |
          cd site  # Make sure we are in the 'site' directory
          npm run build  # Run the build process

      # Install and start a local server to preview the build
      - name: Install http-server
        run: |
          cd site
          npm install -g http-server

      - name: Preview the site (Local Server)
        run: |
          cd site/out
          http-server -p 8080 &  # Run in background on port 8080
          sleep 10  # Allow some time for the server to start
          curl http://localhost:8080  # Test the server
